/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type AddonVersionDetailRes struct {
	Name *string `json:"name"`

	Version *string `json:"version"`

	Deprecated *bool `json:"deprecated"`

	RequiresWorkerNodes *bool `json:"requiresWorkerNodes"`

	ChartRefPattern *string `json:"chartRefPattern,omitempty"`

	ConfigurationSchema map[string]interface{} `json:"configurationSchema,omitempty"`
}
