/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type AddonConfigRes struct {
	Name *string `json:"name"`

	DisplayName *string `json:"displayName"`

	Description *string `json:"description"`

	Category *string `json:"category"`

	Versions []*string `json:"versions"`
}
