/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type ClusterAddonsRes struct {
	Addons []*ClusterAddonRes `json:"addons"`

	TotalCount *int32 `json:"totalCount"`

	Page *int32 `json:"page"`

	Size *int32 `json:"size"`
}
