/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type ClusterAddonRes struct {
	Uuid *string `json:"uuid"`

	ClusterUuid *string `json:"clusterUuid"`

	AddonName *string `json:"addonName"`

	Version *string `json:"version"`

	ConfigurationValues *string `json:"configurationValues"`

	DisplayName *string `json:"displayName,omitempty"`

	Description *string `json:"description,omitempty"`

	Category *string `json:"category,omitempty"`

	Status *string `json:"status"`

	Message *string `json:"message,omitempty"`

	K8sVersion *string `json:"k8sVersion"`

	LatestVersion *string `json:"latestVersion,omitempty"`

	CreateYmdt *string `json:"createYmdt"`

	UpdateYmdt *string `json:"updateYmdt"`
}
