/*
 * vnks
 *
 * <br/>https://nks.apigw.ntruss.com/vnks/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnks

type InstallAddonDto struct {
	AddonName *string `json:"addonName"`

	Version *string `json:"version"`

	ConfigurationValues *string `json:"configurationValues,omitempty"`

	ResolveConflicts *string `json:"resolveConflicts,omitempty"`
}
